package view;

import controller.Controlador;

/**
 *
 * @author usuario
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu(Controlador controller) {
        initComponents(controller);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents(Controlador controller) {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscador = new javax.swing.JButton();
        btnConsultarListas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        chat= new javax.swing.JButton();
        btnClienteFTP=new javax.swing.JButton();
        calculadora= new javax.swing.JButton();
        servidor= new javax.swing.JButton();
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("¿Que desea hacer? ");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("DAM Blinders");
        
        btnClienteFTP.setText("ClienteFTP");
        btnClienteFTP.addActionListener(controller);

        calculadora.setText("Calculadora");
        calculadora.addActionListener(controller);

        servidor.setText("Servidor de archivos");
        servidor.addActionListener(controller);

        btnBuscador.setText("Buscar Peliculas");
        btnBuscador.addActionListener(controller);
        
        chat.setText("Pulse para abrir el chat");
        chat.addActionListener(controller);
        btnConsultarListas.setText("Consultar listas");
        btnConsultarListas.addActionListener(controller);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(controller);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(65, 65, 65)
                                    .addComponent(btnBuscador)
                                    .addGap(65, 65, 65)
                                    .addComponent(calculadora)
                                    .addGap(65, 65, 65)
                                    .addComponent(servidor)

                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                                .addComponent(btnConsultarListas)
                                    .addGap(65, 65, 65)
                            .addComponent(btnClienteFTP))))

                                
                        
                         
                    .addGroup(jPanel1Layout.createSequentialGroup()
                          
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSalir)

                         .addComponent(chat)))
                .addGap(56, 56, 56))
                 
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuscador)
                        .addGap(53, 53, 53)
                        .addComponent(calculadora)
                        .addGap(53, 53, 53)
                        .addComponent(servidor)
                        .addGap(53, 53, 53)
                    .addComponent(btnConsultarListas)
                        .addGap(53, 53, 53)
                    .addComponent(btnClienteFTP))
                .addGap(53, 53, 53)
                .addComponent(btnSalir)
                .addContainerGap(62, Short.MAX_VALUE))
                .addComponent(chat)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscador;
    private javax.swing.JButton btnConsultarListas;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnClienteFTP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton chat;
    private javax.swing.JButton servidor;
    private javax.swing.JButton calculadora;
    // End of variables declaration//GEN-END:variables
}
